#=================================================
# Lisence: MIT
# Author: Texot
#=================================================

name: Build Openwrt Buildenv

on:
  deployment:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Enable experimental features
      run: |
        echo '{
          "experimental": true
        }' | sudo tee /etc/docker/daemon.json
        sudo service docker restart

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        DOCKER_BUILDKIT: 1
      with:
        name: ${{vars.DOCKER_IMAGENAME}}
        username: ${{vars.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD }}
